missing parentheses causing error
when output_format = "csv" some functions throw the error below, because of the misplaced parentheses. 

"C:\Users\\alpha_vantage\alpha_vantage\async_support\alphavantage.py", line 261, in _handle_api_call
    csv_response = csv.reader((await response.text.splitlines()))
AttributeError: 'function' object has no attribute 'splitlines'